# Generated by Django 5.1.1 on 2024-12-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(choices=[('#f50b0b', 'قرمز'), ('#0844f3', 'آبی'), ('#f7f704', 'زرد'), ('#22f704', 'سبز'), ('#f704e8', 'صورتی'), ('#901f89', 'بنفش'), ('#9c939c', 'خاکستری'), ('#ffffff', 'سفید'), ('#000000', 'سیاه'), ('#f2780c', 'نارنجی'), ('#513924', 'قهوه ای'), ('#f3f3f2', 'شیشه ای'), ('##FF66CC', 'چند رنگ')], max_length=255),
        ),
    ]
